# -*- coding: utf-8 -*-
"""Day 1 assignmemt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jlK4XQKi1r8oMq2WSKfRpb_MXJj4_nKZ

Q.1
"""

RAINBOW

print("LETS UPGRADE")

"""Q.2"""

# test case 1
cp= int(input(" Enter Cost Price: "))

sp = int(input(" Enter Sale Price: "))

if cp < sp:
  print("profit")
elif sp < cp:
  print("Loss")
else:
  print("Neither")

# test case 2
cp= int(input(" Enter Cost Price: "))

sp = int(input(" Enter Sale Price: "))

if cp < sp:
  print("profit")
elif sp < cp:
  print("Loss")
else:
  print("Neither")

# test case 3
cp= int(input(" Enter Cost Price: "))

sp = int(input(" Enter Sale Price: "))

if cp < sp:
  print("profit")
elif sp < cp:
  print("Loss")
else:
  print("Neither")

# test case 4
cp= int(input(" Enter Cost Price: "))

sp = int(input(" Enter Sale Price: "))

if cp < sp:
  print("profit")
elif sp < cp:
  print("Loss")
else:
  print("Neither")

# test case 5
cp= int(input(" Enter Cost Price: "))

sp = int(input(" Enter Sale Price: "))

if cp < sp:
  print("profit")
elif sp < cp:
  print("Loss")
else:
  print("Neither")

# test case 6
cp= int(input(" Enter Cost Price: "))

sp = int(input(" Enter Sale Price: "))

if cp < sp:
  print("profit")
elif sp < cp:
  print("Loss")
else:
  print("Neither")

"""Q.3"""

# test case 1
a=int(input("Enter a number: "))
e=80
if (a*e):
  euro=a*e
print(euro)

# test case 2
a=int(input("Enter a number: "))
e=80
if (a*e):
  euro=a*e
print(euro)

# test case 3
a=int(input("Enter a number: "))
e=80
if (a*e):
  euro=a*e
print(euro)

# test case 4
a=int(input("Enter a number: "))
e=80
if (a*e):
  euro=a*e
print(euro)

# test case 5
a=int(input("Enter a number: "))
e=80
if (a*e):
  euro=a*e
print(euro)

# test case 6
a=int(input("Enter a number: "))
e=80
if (a*e):
  euro=a*e
print(euro)

# test case 7
a=int(input("Enter a number: "))
e=80
if (a*e):
  euro=a*e
print(euro)

# test case 8
a=int(input("Enter a number: "))
e=80
if (a*e):
  euro=a*e
print(euro)